{{- if .Values.ingress.enabled -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-secret
spec:
  secretName: {{ .Release.Name }}-secret
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
  commonName: {{ .Release.Name }}.melkouhen.net
  dnsNames:
    - {{ .Release.Name }}.melkouhen.net
  acme:
    config:
      - dns01:
          ingressClass: nginx
        domains:
          - {{ .Release.Name }}.melkouhen.net
  {{- end }}